spine1:
  hostname: 172.20.20.11
  platform: eos
  username: admin
  password: admin 
  groups:
    - spine 
  connection_options:
    netmiko:
      extras:
        secret: admin
  data:
    loopback_ip: 10.0.0.1
  
spine2: 
  hostname: 172.20.20.12
  platform: eos 
  username: admin
  password: admin
  groups:
    - spine
  connection_options:
    netmiko:
      extras:
        secret: admin
  data: 
   loopback_ip: 10.0.0.2

leaf1:
  hostname: 172.20.20.13
  platform: eos 
  username: admin
  password: admin 
  groups:
    - leaf 
  connection_options:
    netmiko:
      extras:
        secret: admin
  data:
    loopback_ip: 10.0.1.1

leaf2:
  hostname: 172.20.20.14
  platform: eos 
  username: admin
  password: admin
  groups:
      - leaf
  connection_options:
    netmiko:
      extras:
        secret: admin 
  data:
    loopback_ip: 10.0.1.2