[spine]
spine1 ansible_host=172.20.20.11
spine2 ansible_host=172.20.20.12

[leaf]
leaf1 ansible_host=172.20.20.13
leaf2 ansible_host=172.20.20.14

[network:children]
spine
leaf

[network:vars]
ansible_user=admin
ansible_password=admin
ansible_network_os=eos
ansible_connection=network_cli
ansible_become=yes
ansible_become_method=enable