frr version 8.4
frr defaults traditional
hostname frr
!
interface eth1
 ip address 10.1.2.1/31
!
interface eth2
 ip address 10.1.2.3/31
!
interface lo
 ip address 10.0.2.1/32
!
router bgp 65000
 no bgp ebgp-requires-policy
 neighbor 10.1.2.0 remote-as 65001
 neighbor 10.1.2.2 remote-as 65002
 !
 address-family ipv4 unicast
  neighbor 10.1.2.0 activate
  neighbor 10.1.2.2 activate
  network 10.0.2.1/32
 exit-address-family
!
line vty
!
end