frr version 8.4_git
frr defaults traditional
hostname frr
no ipv6 forwarding
!
interface eth1
 ip address 10.1.2.1/31
exit
!
interface eth2
 ip address 10.1.2.3/31
exit
!
interface lo
 ip address 10.0.2.1/32
exit
!
router bgp 65000
 no bgp ebgp-requires-policy
 neighbor 10.1.2.0 remote-as 65001
 neighbor 10.1.2.2 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.0.2.1/32
 exit-address-family
exit
!
